#!/bin/sh

# Prints the current volume or 🔇 if muted.
# Prints 🔈, 🔉 or 🔊 depending on the volume level.
# Prints 🎧 if paired to a bluetooth device.

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer -t ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
	3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ $(pamixer --get-mute) = true ] && echo 🔇 && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

# Bluetooth
paired=$(bluetoothctl info | grep Paired | cut -d ' ' -f 2)
[ "$paired" = "yes" ] && icon+="🎧"

echo "$icon$vol%"
