#!/bin/sh

case $1 in
	"")
		echo "What do you want to sync?"
		;;
	sdg)
		make -C ~/uni/SDG2/project/arkanopi
		file=~/uni/SDG2/project/arkanopi/arkanopi
		rsync $file pi@pi.ciencre.xyz:/home/pi/
		;;
	*)
		echo "Wrong sync option"
		;;
  esac
