#!/bin/sh

postrun() { # Stuff to run to clean up.
	setwallpaper		# Fix background if screen size/arangement has changed.
	setkeyboard		# Re-remap keys if keyboard added (for laptop bases)
	{ killall dunst ; setsid -f dunst ;} >/dev/null 2>&1 # Restart dunst to ensure proper location on screen
	}

# Get all possible displays
allposs=$(xrandr -q | grep "connected")

# Get all connected screens.
screens=$(echo "$allposs" | awk '/ connected/ {print $1}')

# If there's only one screen
[ "$(echo "$screens" | wc -l)" -lt 2 ] &&
	{ onescreen "$screens"; postrun; notify-send "💻 Only one screen detected." "Using it in its optimal settings...";  exit ;}

primary=$(echo "$screens" | awk 'NR==1{print $1}')
# secondary=$(echo "$screens" | awk 'NR==2{print $1}')
direction='right'
cmd="xrandr --output ${primary} --auto --scale 1.0x1.0"
for screen in $(echo "$screens" | awk 'NR>1')
do
	cmd="${cmd} --output ${screen} --"$direction"-of $primary --auto --scale 1.0x1.0"
done

echo $cmd
$cmd

# xrandr --output "$primary" --auto --scale 1.0x1.0 --output "$secondary" --"$direction"-of "$primary" --auto --scale 1.0x1.0
