#!/bin/bash

## Using setxkbmap
setxkbmap 	-layout us_local,es \
			-variant altgr-intl, \
			-option \
			-option \
				grp:ctrls_toggle, \
				shift:both_capslock, \
				caps:super, \
				terminate:ctrl_alt_bksp, \
				lv3:lwin_switch, \
				numpad:mac
				# lv5:lsgt_switch, \

## Using xmodmap
#xmodmap ~/.local/bin/keymaps/base
#xmodmap ~/.local/bin/keymaps/remaps

# When Caps is pressed alone it behaves as Escape
killall xcape 2>/dev/null
xcape -e 'Super_L=Escape'

# Speed xrate up
xset r rate 300 50
