#!/bin/sh
search=search.brave.com

bm_file=~/.local/bin/files/bookmarks.md
focus_pid=$(xdotool getwindowfocus)

url=$(grep -v "##" $bm_file | dmenu -l 20 | cut -d "|" -f 2 )

[ -z "$url" ] && exit
[ ! $(echo $url | grep http) ] && url=https://${search}/search?q=$(echo $url | sed 's/ /+/g')

for brave_pid in $(xdotool search --onlyvisible --class 'Brave')
do
	if [ $focus_pid = $brave_pid ]; then
		$BROWSER $url
		exit
	fi
done

$BROWSER --new-window $url
